---
driver:
  name: docker
platforms:
  - name: audit
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: audit-summary
